"""Add approval fields to expenses

Revision ID: 323d84e7364d
Revises: 9d2c54f77e5d
Create Date: 2026-05-15 21:57:24.420007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323d84e7364d'
down_revision: Union[str, Sequence[str], None] = '9d2c54f77e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_employees_users_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_expenses_users_approved_by', 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column('is_admin', existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column('is_superuser', existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column('is_active', existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active', existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column('is_superuser', existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column('is_admin', existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column('role', existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_users_approved_by', type_='foreignkey')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approval_status')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employees_users_user_id', type_='foreignkey')
    # ### end Alembic commands ###
