"""Add brand and capacity fields to equipment

Revision ID: 9d2c54f77e5d
Revises: 926d526a4474
Create Date: 2026-05-15 08:48:51.767927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2c54f77e5d'
down_revision: Union[str, Sequence[str], None] = '926d526a4474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('equipment', sa.Column('capacity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('equipment', 'capacity')
    op.drop_column('equipment', 'brand')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    # ### end Alembic commands ###
