"""Add fuel purchase and expense payment fields

Revision ID: bccbe5b181d4
Revises: 323d84e7364d
Create Date: 2026-05-15 22:59:03.064540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccbe5b181d4'
down_revision: Union[str, Sequence[str], None] = '323d84e7364d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('expenses', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), server_default="unpaid", nullable=False), insert_after='approved_at')
        batch_op.add_column(sa.Column('paid_by', sa.Integer(), nullable=True), insert_after='payment_status')
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True), insert_after='paid_by')
        batch_op.create_foreign_key(batch_op.f('fk_expenses_paid_by_users'), 'users', ['paid_by'], ['id'])

    with op.batch_alter_table('fuel_prices', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('liters', sa.Float(), nullable=True), insert_after='effective_date')
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True), insert_after='liters')
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), server_default="approved", nullable=False), insert_after='total_price')
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True), insert_after='approval_status')
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True), insert_after='approved_by')
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True), insert_after='approved_at')
        batch_op.create_foreign_key(batch_op.f('fk_fuel_prices_approved_by_users'), 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_fuel_prices_created_by_users'), 'users', ['created_by'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_prices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('total_price')
        batch_op.drop_column('liters')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
